// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://matdzcqgvrvvvxajuztj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1hdGR6Y3FndnJ2dnZ4YWp1enRqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5ODc1MzQsImV4cCI6MjA2OTU2MzUzNH0.lXI8P3LPgjB9Sxk3Gg5t7PlzgteElxjZUavwfSdaMxI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});